spring:
  main:
    allow-bean-definition-overriding: true
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #flyWay
  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db/migration